### ISSUE TITLE
"make run" fails to find pywren-config.env

### ISSUE THREAD

**Issue by robertnishihara** [ucbrise/risecamp#30]
This line is causing problems for me when I do `make run` in the root directory.

https://github.com/ucbrise/risecamp/blob/7e1fe7c1b9142bd7c630a97e890bab2ebf5b3899/Makefile#L12

Does the `./pywren-config.env` file exist anywhere.

**Comment by jey** [comment]
Fixed in b7bfa84bfc81904530f8527316c2b5f64604b1c0. Sorry!
