### ISSUE TITLE
Container mismatch

### ISSUE THREAD

**Issue by immesys** [ucbrise/risecamp#53]
Makefile for base container pushes to an image without a tag. The example dockerfile pulls from the `:stable` tag. Sneaky...

**Comment by jey** [comment]
This is intentional but might need better documentation... the idea is that tagging a new `stable` release should be a deliberate choice separate from pushing a `latest` build, which is more like a nightly snapshot. Does that seem reasonable?

**Comment by jey** [comment]
Oh, I see what you mean -- this screws up local development because `make build` no longer updates the dependencies of the sibling directories. Doh.

**Comment by immesys** [comment]
Yeah :)

**Comment by jey** [comment]
OK, I'm fixing this by just switching to using the default of `latest` everywhere, that way everything works more intuitively, and people can still use non-`latest` tags to refer to specific builds (e.g. for testing).
