### ISSUE TITLE
integration exercise has wrong DOCKER_TAG

### ISSUE THREAD

**Issue by jey** [ucbrise/risecamp#56]
@pcmoritz, can you fix the `DOCKER_TAG` in the `integration/` dir? thanks!

https://github.com/ucbrise/risecamp/blob/d94bf78cae90161b43cf2f6b57d8cc327460e501/integration/Makefile#L3

**Comment by pcmoritz** [comment]
@jey Sorry just saw this, what do you think the right tag should be? I put down ucbjey/risecamp2018-base:stable initially, is that not a good one to work on top of?

**Comment by jey** [comment]
Hi @pcmoritz, you'll have to sign up for a Docker Hub account and create a name for it as described at: https://github.com/ucbrise/risecamp/blob/c5504c8188eeb1a88a9be471207a588f8e8a9165/example/README.md#getting-started

**Comment by jey** [comment]
Looks like this is fixed. Thanks!
