### ISSUE TITLE
External services

### ISSUE THREAD

**Issue by immesys** [ucbrise/risecamp#72]
I hear we are preparing to release the risecamp tutorials as a standalone artifact that the general public can run.

As you know, the WAVE tutorial has people interact with other people. To facilitate that, there are two external services that run. One is the WAVE storage tier, which allows people to receive permissions granted by other people. The other is the MQTT server which allows people to send messages to each other.

Shane suggested we try remove these dependencies so we don't have to support them indefinitely. 

One solution I can think of is to run both MQTT and the WAVE storage inside every container. Then when you have two notebooks wanting to work with each other, they must fill in the IP address of a "master" notebook that they then connect to. Not nearly as smooth as what we had at the camp, but hey.

Any ideas?

**Comment by jey** [comment]
>One solution I can think of is to run both MQTT and the WAVE storage inside every container. Then when you have two notebooks wanting to work with each other, they must fill in the IP address of a "master" notebook that they then connect to. 

Sounds good to me.

**Comment by jey** [comment]
Can this be done by end of week? Thanks

**Comment by immesys** [comment]
It could, but I would ideally like to do it after my current paper deadline (after the 15th). Given that it should work as-is, is there any harm in shipping it like this and then updating the repo later to the new solution? The current code should continue to work for a few months anyway, the new code is just so that it can last indefinitely.

**Comment by jey** [comment]
Awesome, thanks for the clarification. No rush then, and I'll ship it as-is.

**Comment by jegonzal** [comment]
Is this resolved?  It would be good to close the issue.
