### ISSUE TITLE
Recent Makefile.inc update breaks other projects, including example

### ISSUE THREAD

**Issue by rbavishi** [ucbrise/risecamp#84]
A recent update to `Makefile.inc` changes the set of `DOCKER_RUN_FLAGS` by adding a `--network "test-net"` which seems to cause `make run` to fail by default on other projects (including `example`). The error is `docker: Error response from daemon: network test-net not found.`

@chester-leung is there a way around this?

**Comment by chester-leung** [comment]
This flag enables intercontainer communication, which we need for our tutorial. Let's remove the flag for now so it doesn't break any builds, and I can work with Jey offline to figure this out.

**Comment by jey** [comment]
@chester-leung: please add docker flags that are specific to your project to `mc2/Makefile` using `DOCKER_RUN_FLAGS`. An example can be found here: https://github.com/ucbrise/risecamp/blob/risecamp2018/ray/Makefile

Please also revert the changes to `Makefile.inc`. Thanks!

**Comment by devin-petersohn** [comment]
Should be fixed by #88
